### ISSUE TITLE
getAPI needs working code

### ISSUE THREAD

**Issue by TIMcre** [j-kottkamp/Stock-Screener#6]
The entire file getAPI.py needs to be reworked.

 The get_api_key function needs to be rewritten completly to work corectly.

The valid_api_key function needs to get a logic impelmtaion to check the status of the api key.

The api_key function may need a check to see if api key that we got is really valid.

The api_key function may need to get a different storing system for the current api key (Caching of the current one for faster replies)

**Comment by j-kottkamp** [comment]
True
